#main.yml - defines a GitHub Actions workflow that sets up a Python environment, installs dependencies, checks the code for style issues, and runs the hello.py script. 

#Sets the name of the workflow
name: CI/CD Pipeline

#Specify the event that trigger the workflow -  In this case, the workflow is triggered whenever you push changes to your GitHub repository.
on: [push]

#Define a job called 'build.'
jobs:
  build:
  #Define type of runner(virtual environment) - Ubuntu latest version
    runs-on: ubuntu-latest
    
    #Definition of the steps to be executed within the build job - steps.
    steps:
    #Check out repository using the 'actions/checkout'
    - name: Check out repository
      uses: actions/checkout@v2
    
    #Setup Python environment on the runner using the 'actions/setup-python.' The 'with' block specifies the Python version to use. 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    #Install dependencies required for the project. Upgrade 'pip' package manager and  install the flake8 Python linting tool.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 hello.py
        
    #Run flake8 linter on hello.py. It checks the code for style issues and errors. If any issues are found, this step will fail, and the workflow will stop executing.   
    - name: Run script
      run: |
        python hello.py
